---
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
builds:
  # the majority of bins
  - id: "{{ .ProjectName }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{ .CommitDate }}' -X 'main.builtBy=github.com/goreleaser/goreleaser-action'"
  # only support windows_amd64
  - id: "{{ .ProjectName }}_windows"
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - "-s -w -X 'main.version={{.Version}}' -X 'main.commit={{.Commit}}' -X 'main.date={{ .CommitDate }}' -X 'main.builtBy=github.com/goreleaser/goreleaser-action'"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    id: binary
    format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  footer: |
    # OCI image:

    ```
    {{ .Env.image_name }}
    ```

    verify signature using `cosign`:

    ```
    cat <<EOF > cosign.pub
    {{ .Env.cosignPub }}
    EOF

    cosign verify --key cosign.pub {{ .Env.image_name }};

    rm -f cosign.pub
    ```
